#if !canImport(ObjectiveC)
import XCTest

extension FluentExtensionsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FluentExtensionsTests = [
        ("testRandomRangeElement", testRandomRangeElement),
        ("testRandomSubrange", testRandomSubrange),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(FluentExtensionsTests.__allTests__FluentExtensionsTests),
    ]
}
#endif
